# Generated by Django 5.2.7 on 2025-11-04 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dealer name (e.g., Henry Schein)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("website", models.URLField(help_text="Dealer website URL")),
                (
                    "spider_class",
                    models.CharField(
                        help_text="Spider class name (e.g., HenryScheinSpider)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable scraping for this dealer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dealers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YourProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "your_sku",
                    models.CharField(
                        help_text="Your internal SKU", max_length=100, unique=True
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, help_text="Manufacturer Part Number", max_length=100
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="Your product name", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Your Product",
                "verbose_name_plural": "Your Products",
                "db_table": "your_products",
                "ordering": ["your_sku"],
            },
        ),
        migrations.CreateModel(
            name="DealerProductListingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealer_sku", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=500)),
                ("description_features", models.TextField(blank=True)),
                ("specifications", models.TextField(blank=True)),
                ("product_url", models.URLField(max_length=1000)),
                (
                    "scraped_at",
                    models.DateTimeField(help_text="When this snapshot was taken"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_history",
                        to="scrapers.dealer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Listing History",
                "verbose_name_plural": "Product Listing History",
                "db_table": "dealer_product_listing_history",
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["dealer", "dealer_sku", "-scraped_at"],
                        name="dealer_prod_dealer__252d80_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DealerProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Product name on dealer site", max_length=500
                    ),
                ),
                (
                    "dealer_sku",
                    models.CharField(
                        help_text="Dealer SKU/Part Number", max_length=100
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, help_text="Manufacturer Part Number", max_length=100
                    ),
                ),
                (
                    "description_features",
                    models.TextField(
                        blank=True,
                        help_text="Combined description and features from dealer site",
                    ),
                ),
                (
                    "specifications",
                    models.TextField(blank=True, help_text="Technical specifications"),
                ),
                (
                    "product_url",
                    models.URLField(
                        help_text="URL to product on dealer site", max_length=1000
                    ),
                ),
                (
                    "scrape_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last scraped date/time",
                    ),
                ),
                (
                    "content_changed",
                    models.BooleanField(
                        default=False, help_text="Content changed since last scrape"
                    ),
                ),
                (
                    "previous_content_hash",
                    models.CharField(
                        blank=True,
                        help_text="MD5 hash of previous content",
                        max_length=32,
                    ),
                ),
                (
                    "diff_content",
                    models.TextField(
                        blank=True, help_text="Description of what changed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="scrapers.dealer",
                    ),
                ),
                (
                    "your_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to your product catalog (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer_listings",
                        to="scrapers.yourproduct",
                    ),
                ),
            ],
            options={
                "db_table": "dealer_product_listings",
                "ordering": ["-scrape_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["dealer", "dealer_sku"],
                        name="dealer_prod_dealer__93de01_idx",
                    ),
                    models.Index(fields=["mpn"], name="dealer_prod_mpn_d517b2_idx"),
                    models.Index(
                        fields=["content_changed"],
                        name="dealer_prod_content_3e3868_idx",
                    ),
                ],
                "unique_together": {("dealer", "dealer_sku")},
            },
        ),
    ]
